server:
  port: 8081
spring:
  datasource:
    username: root
    password: duhonglei
    url: jdbc:mysql://localhost:3306/shiro?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # Spring Boot默认是不注入这些属性值的，需要自己绑定
      # druid 数据源专有配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      # 配置监控统计拦截的filters，stat：监控统计、log4j：日志记录、wall：防御sql注入
      # 如果允许时报错 java.lang.ClassNotFoundException:org.apache.log4j.Priority
      # 则导入 log4j 依赖即可
      filters: stat,wall,log4j
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
mybatis:
  type-aliases-package: com.wenze.shiro.model
  mapper-locations: classpath:mapper/*.xml